name: Cases Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cases_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.17'
    - run: go test ./...
